/**
 * Re-export the users table and enums from auth.ts.
 *
 * The canonical definition lives in auth.ts (generated by Better Auth CLI
 * and patched by scripts/merge-schemas.ts).  This file exists so that all
 * existing schema imports like `from './users'` continue to work.
 */
export { users, themeEnum, planEnum } from './auth';
